# SSH Tunnels Configuration
# Format: id|label|local_port:remote_host:remote_port|ssh_host
# Example: work-db|Work Database|5432:localhost:5432|work-server

bilby-rails|3000|3000:localhost:3000|bilby
bilby-rails|4000|4000:localhost:4000|bilby
